### PR TITLE
Added a nice theme for meilix- (Solves- #358)

### LINKED ISSUE #358: Setting a nice default theme for the MeilixISO
- Issue type: Feature request 

### Short description

Current meilix default theme(frost for xenial)
screenshot from 2018-12-14 02-00-18 
does'nt look nice and is very dark
We should use another theme for the MeilixISO( selfmade or through options) available online

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 
 - Software source: 

### Expected behaviour

Changing the default meilix-desktop theme to a better one 
### Description

We have to change the lxqt theme to a nice one, afterwards we can change wallpaper through the meilix builds
We can create a new lxqt theme related to fossasia or we can use a nice theme from the following options:
https://www.pcsuggest.com/best-lxqt-themes/
https://www.opendesktop.org/browse/cat/446/ord/top/

### PR DESCRIPTION
**Pull request by pranav1698**
### Short description
I have added a nice default theme for meilix custom ISO
The previous default settings package contained this theme; I have removed all the files for the external packages and only those configuration files remain that are for the proper viewing of the theme and the proper settings of the icons and other options on the desktop enviroment

I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

screenshot from 2018-12-14 19-22-53

Link for the ISO: https://github.com/pranav1698/meilix/releases/tag/untagged-6825ceab6ce464d1617b

Fixes #358

### CODE REVIEW

**Comment by tabesin** [comment]
This PR includes lots of unrelated settings changes.

**Comment by pranav1698** [comment]
@tabesin I am little confused for this particular pr what files to keep and what files to delete?
Please suggest the changes

**Comment by pranav1698** [comment]
For this pr:
Just the default folder for the theme usually in /usr/share/lxqt/themes/meilix is required 
I am confused I have to keep only the files for meilix theme and delete all other files or any other files in meilix-default settings is required @xeon-zolt 

I have done nothing with the conf files atleast for this pr just deleted some of them which was not related to the pr

**Comment by xeon-zolt** [comment]
I still don't know why force install is required  also create a new branch and keep that folder I will not merge all those files

**Comment by tabesin** [comment]
New Theme should only require changes in the artwork package.

**Comment by pranav1698** [comment]
Okay I will make the required changes in the artwork repo, and then in the meilix repo for the theme purpose

**Pull request closed without merging**
