### PR TITLE
Revert "parallel building"

### PR DESCRIPTION
**Pull request by meets2tarun**
Reverts fossasia/meilix#72

### CODE REVIEW

**Comment by xeon-zolt** [comment]
@meets2tarun I don't understand this first you want me to approve the commit now you want to revert it you don't even wait for it to be approved

**Comment by meets2tarun** [comment]
Since the last one is failing the Travis check.

**Comment by xeon-zolt** [comment]
but it did not when it was approved

**Comment by meets2tarun** [comment]
It is https://travis-ci.org/fossasia/meilix/jobs/251382715
that's why I revert it back

**Comment by meets2tarun** [comment]
@xeon-zolt https://travis-ci.org/fossasia/meilix/builds/254056447#L8591
I get this as an non-deployment message but the in the release section the iso gets deployed
https://github.com/fossasia/meilix/releases/tag/untagged-f24c71a9f413aac14379

**Pull request merged**
