### PR TITLE
Resolves #8 and a part of #3, Added this github repository as a PPA

### LINKED ISSUE #8: Repository for distro
The goal is to keep our files on our own server and have our own repository. What is the simplest model to get this for now?

### PR DESCRIPTION
**Pull request by Abhi2424shek**
@mariobehling thanks for that tutorial though it was a bit old managed to solve the issue, please review and merge. apt will now also search for packages in the github repository (/sources directory)

**Remember the PPA is a automatic (complicated) PPA and not a trivial one...**

I also updated the readme as per your request, so that it would guide the new coders.

**Resolves issues: #8 and part of issue #3.
Link to GCI Task: [GCI task](https://codein.withgoogle.com/dashboard/task-instances/5866565809471488/)**

_Note: Travis is not failing because of the files changed in this PR, I know you know it but just a reminder ;)_

And lastly,
Happy coding :)

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
ping @mariobehling Link to GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5866565809471488/
;)

**Comment by mariobehling** [comment]
Did you try if that works with the master branch? The idea was to host it on a gh-pages branch originally, right?

**Comment by Abhi2424shek** [comment]
@mariobehling go to settings and change the setting there to host on the master branch

**Comment by mariobehling** [comment]
ok. Thank you.

**Comment by Abhi2424shek** [comment]
No mentions,,,

**Comment by mariobehling** [comment]
On second thoughts: Could we move the repository to gh-pages. So Master can be used for any code related items and gh-pages will be a stable repository?

**Comment by Abhi2424shek** [comment]
@mariobehling that would lead to bad results as to add a metapackage the user will have to switch branches or make two PR's if we put them in two branches!

**Comment by mariobehling** [comment]
The Master branch is not organized in a structure of a repository for packages. The final step should be that the github pages branch holds the repo and it autogenerated through a script. We can use travis to execute this.

**Comment by Abhi2424shek** [comment]
@mariobehling sure working on it then...

**Comment by Abhi2424shek** [comment]
We will have a new issue for it. Can't we @mariobehling

**Pull request merged**
