### PR TITLE
Adds packages in build.sh to be provied by Travis

### LINKED ISSUE #40: Travis CI is taking a long time to compile the code
The average build time is around 27mins or so, it would have been better if we could investigate faster CIs and move the build function to there and keep the Content Delivery with Travis (metapackage pushing to gh-pages). What are your thoughts?

### PR DESCRIPTION
**Pull request by abishekvashok**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message` >> Mentioned the issue number in the PR body

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

The packages required on the system which is used to make the iso were fetched by build.sh
using apt-get. Travis Ci allows packages to be predefined in the build environment which would
decrease the build time required.

Fixes #40 

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>

### CODE REVIEW

**Comment by abishekvashok** [comment]
Please merge only after comparing build times.

**Comment by tabesin** [comment]
Question: In the travis chroot build environment within the travis environment we use zesty while in the travis-ci they currently use trusty. Does that patch apply to the trusty environment of Travis-ci then? Is that even needed?

**Comment by abishekvashok** [comment]
Which patch are you referring to @tabesin this one?

**Comment by abishekvashok** [comment]
Seems like it saves 8mins as of the previous builds

**Comment by tabesin** [comment]
72a9195a7abe2443c8d9a8ce7fce1e6ed4794925

**Comment by abishekvashok** [comment]
@tabesin we download some packages before entering chroot environment. By specifying those packages in the .travis.yml, Travis provides those packages beforehand into the docker container it will run our script. So, when the script runs `apt-get` it won't download those packages again. They are specified outside the chroot environment because they are expected to be at the system the build.sh script is run to get the iso. So, by this PR we get a sharp decrease in build time as the internet in the Travis ci container is not so fast so the package download time can be avoided.

Build time is now 18 mins.


Note: i didnt remove those packages off build.sh so that build.sh works outside Travis CI as well.

**Comment by tabesin** [comment]
Let's try.

**Pull request merged**
