### PR TITLE
Fixes #135 add screensaver turnoff to .profile

### LINKED ISSUE #135: Disabling Screen Saver in meilix
- Issue type: Feature request 

### Short description

We need to disable the screen saver in the meiix ISO

### Usecase

This feature is one of the requirement as mention https://github.com/fossasia/labs.fossasia.org/issues/135
### Description

To disable we have to edit a config file located in or where should the screen saver switch-off setting go into .xsessionrc or .xinitrc or .profile?

### PR DESCRIPTION
**Pull request by tabesin**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
@tabesin 
Can you provide the release ISO link so that we can test the PR and for that, I think you need to temporarily edit the .travis.yml with your secure API?

**Comment by meets2tarun** [comment]
And this doesn't work this way:
First we need just to add the file to this location `meilix-default-settings/etc/skel/.profile`
then debuild the meilix-default-settings metapackage then it will automatically include file here `meilix-default-settings/debian/meilix-default-settings/etc/skel/.profile`

**Comment by tabesin** [comment]
Cause we do via debuild.sh
rm -rf meilix-default-settings/debian/meilix-default-settings
it does not matter what is there anyway. 
Note that I made the same changes at both places.

**Comment by meets2tarun** [comment]
And if I include only the `meilix-default-settings/etc/skel/.profile` and debuild the package, then we will find that `meilix-default-settings/debian/meilix-default-settings/etc/skel/.profile` will automatically exist at that location without manually creating it.

**Comment by tabesin** [comment]
Of course. With other words we can delete it also on the code branch

**Comment by meets2tarun** [comment]
But the real concern is:
That the debuild.sh script should automatically build it for us rather than we do it every time.
I mean we just need to edit the meilix-default-setting not to debuild it.

**Comment by tabesin** [comment]
I added the missing package. The current build problem relates to Travis deployment, not building.

>  98.55% done, estimate finish Thu Aug  3 18:27:23 2017
>  99.18% done, estimate finish Thu Aug  3 18:27:23 2017
>  99.81% done, estimate finish Thu Aug  3 18:27:23 2017
> Total translation table size: 2048
> Total rockridge attributes bytes: 34191
> Total directory bytes: 147226
> Path table size(bytes): 972
> Max brk space used 5d000
> 791504 extents written (1545 MB)
> 
> travis_time:end:11014017:start=1501783676810557383,finish=1501784846904456201,duration=1170093898818
> [0K
> [32;1mThe command "./build.sh" exited with 0.[0m
> travis_fold:start:before_deploy.1
> [0Ktravis_time:start:2deea73c
> [0K$ export image_name="`echo *.iso`"
> ---- snip -----
> travis_fold:start:dpl.2
> [33mPreparing deploy[0m
> 
> travis_fold:end:dpl.2
> failed to deploy

**Comment by meets2tarun** [comment]
From the next time we only have to add something only to this location:
` meilix-default-settings/....` not in the  `meilix-default-settings/debian/meilix-default-settings/....`

**Comment by tabesin** [comment]
No no, my current task is to remove this tree from GIT entirely. However, it seems there are more files below Debian folder that might be useful as a reference in the future, so I will keep a copy.

**Pull request merged**
