### PR TITLE
Added this github repository as apt-repository

### PR DESCRIPTION
**Pull request by Abhi2424shek**
@mariobehling here you go.

I created a domain for free at meilixsources.gq (you can move it easily to your new domain if you want), for hosting I had digital ocean, I am using the 20$s per month solution, it can be used for two months as I have only 47$ left. So please consider upgrading or getting a new server.

The sources are hotsed down now and it is added to the apt/sources.list.d file.

This github repository will be set to auto sync with the webserver via Travis CI. When a PR is merged all the metapackages are sent to the server via ftp, with the .deb files in /sources/binary and .sources files into /sources/sources directory respectively. I will give a PR for that just a second!

I am giving seperate PR's because both are for two different reasons and the second one may seem a bit to complicated.

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please add information about the repo setup and what technologies you are using to the Readme.md.

**Comment by Abhi2424shek** [comment]
@mariobehling just a sec I am setting them up beware that this will last only for 2months before that you should purchase one...

**Comment by mariobehling** [comment]
Please do not create new branches in the repo but make pull requests from your private repository only to keep the standard workflow in the org. Cheers.

**Comment by Abhi2424shek** [comment]
@mariobehling sorry for that cheers.

**Pull request merged**
