### PR TITLE
Chromium browser config

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue xumber in the pull request commit message `Fixes #<number> commit message`
#67 
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
browser
LXQt on meilix with the chromium browser having the susper as default search engine and homepage

**Comment by xeon-zolt** [comment]
i think it should be part of master not generator

**Comment by meets2tarun** [comment]
This needs to go into the master branch of fossasia.
Therefore closing it.

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/pull/91

**Pull request closed without merging**
