### PR TITLE
changing word `ap` to `apt` in chroot_reconst.sh

### LINKED ISSUE #435: changes in chroot_reconst.sh
- Issue type: Bug report 

### Short description

in line 64 the command is written `ap-get -qq -y install git`

### Steps to reproduce

1.  changing command to `apt-get -qq -y install git`

### PR DESCRIPTION
**Pull request by rpotter12**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #435

### CODE REVIEW

**Comment by xeon-zolt** [comment]
still why git is installed by default?

**Comment by pranav1698** [comment]
Requested by mario in one of the roadblock issues

**Comment by xeon-zolt** [comment]
@pranav1698 can you point me to that issue

**Comment by pranav1698** [comment]
In this one: https://github.com/fossasia/meilix-generator/issues/121

**Pull request merged**
