### PR TITLE
Added default desktop

### LINKED ISSUE #242: Multiple window managers present and no default one in skel
- Issue type: Bug report
### Short description

multiple window mangers are present and I personally dont feel very good about it ( WHY ? )
we should use only one window manger as default if any window manger installed during addition of packages which should not be the case we should also have a default window manger config inside skel
### Steps to reproduce

1. Boot in live moe
### Expected behaviour

should show the DE LXQT without asking for any configuration
### Actual behaviour

 asks for required configuration

screenshot from 2018-03-11 22-54-57

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #242

### CODE REVIEW

**Comment by meets2tarun** [comment]
screen shot 2018-06-24 at 09 26 40

**Comment by niccokunzmann** [comment]
I do not understand how it works: How is this file influencing which desktop is being used?

**Comment by meets2tarun** [comment]
https://superuser.com/a/686001

**Comment by xeon-zolt** [comment]
first question why plasma is present? how it gets installed if you can grep which package requires plasma as the dependency (cause it's also increasing the size of ISO) and I do not understand how it solves  #242
@meets2tarun please add more details 
ThankYou

**Comment by meets2tarun** [comment]
Plasma is installed by some dependency, but actually plasma.desktop never load(in case when we intentionally want). 
/usr/share/xsessions contains the name of the desktops which can be load. The [file](https://github.com/fossasia/meilix/pull/282/files#diff-4342640c51a9529cd883981c9c469730) `.dmrc` in the home directory will help to load the particular desktop.

Thanks

**Comment by xeon-zolt** [comment]
we should remove/replace the package that installs plasma and not try hackish way to reach the goal

**Pull request merged**
