### PR TITLE
ubuntu 16.04 onwards dont use /lib for plymouth it uses /usr/share

### PR DESCRIPTION
**Pull request by xeon-zolt**
### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message` 
i have added a debuild so that plymouth theme can be rebuilt on changes and fixed the theme location from /lib to /usr/share
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by tabesin** [comment]
Please consider to rebase the legacy plymouth theme on current ubuntu plymouth theme packages. Also consider the build error.

**Comment by xeon-zolt** [comment]
checking that only what broke it

**Comment by tabesin** [comment]
Let's ship it then.

**Comment by abishekvashok** [comment]
@tabesin please use the `squash and merge` button to pull a pr which contains more than 1 PRs :)

**Pull request merged**
