### PR TITLE
Fix to turn screensaver off

### LINKED ISSUE #135: Disabling Screen Saver in meilix
- Issue type: Feature request 

### Short description

We need to disable the screen saver in the meiix ISO

### Usecase

This feature is one of the requirement as mention https://github.com/fossasia/labs.fossasia.org/issues/135
### Description

To disable we have to edit a config file located in or where should the screen saver switch-off setting go into .xsessionrc or .xinitrc or .profile?

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
Fixes #135 
This PR will turn off the screen-saver in the meilix ISO
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
> wrong key

I used my key instead of FOSSASIA to get the release.

**Comment by tabesin** [comment]
The other key is your key.

But to not confuse you, all I know is that this key you changed would breaks the deploy, and this PR is about Fossasia:Meilix repo.

**Comment by meets2tarun** [comment]
After testing and founding that the PR will work, I'll revert the key back to FOSSASIA:meilix.

**Comment by tabesin** [comment]
Maybe I can add also your key to the repo. Will check.

**Comment by meets2tarun** [comment]
My own key will work for meets2tarun:meilix only and in the fossasia:meilix

**Comment by tabesin** [comment]
What we need for the main repo the key "tVVKOM...Mrc="

**Comment by tabesin** [comment]
So I changed the key, this way it is supposed to work

**Pull request merged**
