### PR TITLE
Edited Readme

### PR DESCRIPTION
**Pull request by meets2tarun**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, I see you improved the README file.
There is also the travis file changed. If we merge this, I fear, we may loose the working of the token.
What do you think?

**Comment by meets2tarun** [comment]
Should I replace that travis line ?
But the problem is that that secure key works fine with me to test the build on travis but not the secure key which is the original one ?

**Comment by niccokunzmann** [comment]
The secure key is encrypted and can only be encrypted for one repository. Otherwise it could be stolen.

**Comment by meets2tarun** [comment]
The secure key I used can help me to compile the build using travis. The secure key which is originally in .travis.yml file does not the compile the build.
So if I make the changes and if make a P.R with the old secure key then it will not pass the travis check.

**Comment by niccokunzmann** [comment]
Let's try it.

**Comment by Abhi2424shek** [comment]
@meets2tarun:
>So if I make the changes and if make a P.R with the old secure key then it will not pass the travis check.
It will pass as deployment is not done for PRs.
Secure keys will be totally useless in PRs.
Forks are not equal to repositories, each secure key contains identity of its repository so the build may fail for you, but you could always not include a change in a commit, as both yours and the current repository here would need two secure keys.

So the old one was and will be working fine and not the new one. It had failed the build.
(PR passed and not the merge commit as we don't deploy for PRs and only for commits and Travis treats a merge commit just like a regular commit)

You can always discard changes for particular files and not include the changes in git, this can be achieved by running `git reset HEAD (file name goes here along with its path from this directory)`.

By the way we need to get the old token back to get releases back in action :)

Thanks for the read me update though :)

**Pull request merged**
