### PR TITLE
Initializing the gh-pages branch

### PR DESCRIPTION
**Pull request by Abhi2424shek**
We just need the conf, db, dists, incoming and pool directories to host the sources and here they are on the gh-pages branch. I also added a index page so that the url when tried on the browser look good!

There is also a followup for the master branch in PR #15 
This PR and PR #15 was done as part of GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5035394410217472/

Live preview: https://abhi2424shek.github.io/meilix/
[Frontend page only, the sources will be available only via apt]
@mariobehling please review and merge

### CODE REVIEW

**Comment by mariobehling** [comment]
@Abhi2424shek Any idea why codacy checks are taking so long?

**Comment by Abhi2424shek** [comment]
I would just restart it by closing and opening this PR

**Comment by Abhi2424shek** [comment]
gh-pages is not enabled for codacy please enable it @mariobehling

**Comment by Abhi2424shek** [comment]
It's enabled now, let's wait for the results..

**Comment by Abhi2424shek** [comment]
Yep codacy is ok now @mariobehling

**Comment by niccokunzmann** [comment]
@Abhi2424shek, could it be that you delete all files in the branch because it has nothing to do with the master branch? In this case, we could also check out a branch with --orphan.
Is it this way, that those files are not needed?

**Comment by Abhi2424shek** [comment]
Those files are needed only for the master branch, when @mariobehling created this branch, he created a clone of the master branch. We are hosting the metapackages here in the apt.

Here is the directory structure @niccokunzmann:
master - includes the meilix OS
gh-pages - hosts the metapackages

We could have hosted it on launchpad but since we want to use github we are using this branch policy currebtly.

gh-pages would be updated when a new metapackage is added or updated on the master branch via Travis.

**Comment by Abhi2424shek** [comment]
Shall I merge it @niccokunzmann

**Comment by niccokunzmann** [comment]
Seems ok for me.

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
