### PR TITLE
Fixes #121: Removed about-lxqt

### LINKED ISSUE #121: Disable About LXQT label in menu
- Issue type: Feature request 

### Short description
Disable the display of the about-lxqt entry in the menu.
(on a user system this could be done via "menulibre"; then find out what it does)

fossasiatheme

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
Fixes #121 
### Short description
I had deleted abou-lxqt file from `meilix-default-settings/etc/skel/.local/usr/share/applications`
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
Please test the Github Release ISO or give me the link to test it.
Thank you

**Comment by meets2tarun** [comment]
https://github.com/vaibhavsingh97/meilix/releases/tag/untagged-5c036aaa9e779a96eb30

**Comment by xeon-zolt** [comment]
please post a screen shot as a verification proof after testing

**Comment by vaibhavsingh97** [comment]
@meets2tarun @xeon-zolt This is the latest release https://github.com/vaibhavsingh97/meilix/releases/tag/untagged-3c26b22cc6f4aade5cf6. Sorry i don't have good internet connection so i can't test

**Comment by meets2tarun** [comment]
@vaibhavsingh97 
That's not the issue, I'll test it for you anyitme

**Comment by tabesin** [comment]
The file in meilix-default-settings/etc/skel/.local/usr/share/applications is supposed to be a no-show setting that would end up in ~/.local/usr/share/applications but doesn't.

The file you edit is the supposed local custom fix.

**Comment by meets2tarun** [comment]
@vaibhavsingh97 
I checked the link, the issue still presist.

**Comment by tabesin** [comment]
Of course.

**Comment by vaibhavsingh97** [comment]
@tabesin @meets2tarun I will look into this 👍

**Pull request closed without merging**
