### PR TITLE
icons for Meilix

### PR DESCRIPTION
**Pull request by xeon-zolt**
### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `
Fixes Adds better icon theme

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
Please improve the PR by editing `meilix-default-settings/etc/skel/.config/lxqt/lxqt.conf` this part instead of `meilix-default-settings/debian/meilix-default-settings/etc/skel/.config/lxqt/lxqt.conf`

**Comment by tabesin** [comment]
Ok, the point is in short, look at the debuild script, the whole space you are edting it will be deleted prior to debuild, so please take the path meets2tarun pointed at.

**Comment by meets2tarun** [comment]
Everything is working fine except that panel icon (start icon)

screenshot_zol5t_2017-08-09_10 31 04

**Comment by xeon-zolt** [comment]
hmm, will add them to theme in pull request for theme

**Comment by tabesin** [comment]
I will merge the PR but please consider to rename the folder to low-case "meilix"

**Comment by xeon-zolt** [comment]
ok i will fix it in pull request with theme

**Pull request merged**
