### PR TITLE
add Github deploy

### PR DESCRIPTION
**Pull request by niccokunzmann**
I added the Github deploy of the meilix iso.
Currently, this is done for every commit on the master branch.

**to do:**

- To enable this, either I become a contributor who can create releases or someone changes the access token for github.
- It is possible to run this only for tags I can add this for you, if it is needed.

Example: https://github.com/CodersOS/meilix/releases

What do you think?

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
What should be the access token changed to @niccokunzmann i have write access, would it do?

**Comment by niccokunzmann** [comment]
You can create an access token here: https://github.com/settings/tokens/new

image

1. Then, you go to your shell and into the meilix repository.
2. install travis: sudo gem install travis - be sure to have `ruby-dev` installed
3. You encrypt the access token `travis encrypt <access token>` The output is `secure: .....`

**Comment by Abhi2424shek** [comment]
But wouldn't it leave my account work like a bot @niccokunzmann we've got a bot here, so can you use it

**Comment by mariobehling** [comment]
@niccokunzmann Awesome idea! I added you to the team with write access. Please proceed.

@Abhi2424shek Please merge the PR when Nicco has added the token. Cheers.

**Comment by Abhi2424shek** [comment]
Sure @mariobwhling I would just deliver the access token pls wait...

**Comment by Abhi2424shek** [comment]
@niccokunzmann here's a token:
`secure: "ILvV+ORxHcfTCBXFx7y3UZRN8Sa6ftNjfeeHwI+MMxX0MuaA4pFxxvgZc8oaxRJNFB6CwIgoAEteTVPZ/yxkPjsDleNruqfOGmLtX4ClDHEWaoiaVS9fPL0cn8glmam+H2He+a+44fOf1pXK29uvmE6P+7C8VluD3f2Q5k0yF8OTGnkQgDJjBRuwxB0n1EHRbeU4WqvNM8RjdOMP7H8kQ0Fbp3IY7fai3YO/TtYfZFYfBS4njcLnlBkWB6WzNI+NTNQNccPVBXmtYx/v5jzUPIi6FUXN8UYpNj5IKyEd7HKahlhHMKGefOC3iQRF9khvlGgxmuyDz/O2YBxtaxsDjO0AnYtBq49orZgy6NkuNWV3pYseCTcUl+gc9406FuKGsoYY4t3PotSTN2XrjKEupC4BER774l8hCS0qvq6HVUuFmusnNzRFpArdePaKJUh6sg2d1vAkNdpOBPrVyUhHz/dMQvkImsbT5GNZ/IDm79XpX9AfgXkWrz25hsFzbOA2vud/VIVTARi0WFnrE4f4310gASG5bRjY/iaxQiTPf9hXNZdIq2LH+XpeL2sUMj5hJWFHTOEyuBeSZCHtTVWlyiPWX70TLkGZJjxSWlY/Yezg60AStVmXxQGJTHK8F97wULkW4YJebl9wSEao3x4AHKkupyg2p2EQd+ZGEiSopZY="`

**Comment by niccokunzmann** [comment]
@Abhi2424shek The API key is included, now.

**Comment by Abhi2424shek** [comment]
@niccokunzmann there must have been some errors in the api token i provided, sorry sir. I gave it as per the given instructions though let me recheck...

**Pull request merged**
