### PR TITLE
Refactoring the file-system manifest- (Solves- #237)

### LINKED ISSUE #237: Refactoring filesystem manifest
Please check if this could be simplified and for what reasons we have this cp chain here:

> sudo chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' >/tmp/manifest.$$
> sudo cp -v /tmp/manifest.$$ image/casper/filesystem.manifest
> sudo cp -v image/casper/filesystem.manifest image/casper/filesystem.manifest-desktop
> rm /tmp/manifest.$$

### PR DESCRIPTION
**Pull request by pranav1698**
### Short description
The code for the creating a manifest is simplified 
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #237

### CODE REVIEW

**Comment by pranav1698** [comment]
Yeah it was passing the tests all of the time
I will test theink for travis and also for the ISO

**Comment by pranav1698** [comment]
Travis build link: https://travis-ci.org/pranav1698/meilix/builds/466521732
LInk to the iso: https://github.com/pranav1698/meilix/releases/tag/untagged-a2d04e297d3a0f45e749

**Comment by pranav1698** [comment]
@tabesin please review now

**Comment by tabesin** [comment]
Okay then, I just wanted to be sure that you tested it in advance.

**Pull request merged**
