### PR TITLE
fixed issue #133 disable desktop notification  

### PR DESCRIPTION
**Pull request by sandeepsajan0**
fixed issue #133 
release ISO file is here   https://github.com/sandeepsajan0/meilix/releases/tag/untagged-fa18ce41e3f0696e0878

### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by sandeepsajan0** [comment]
@meets2tarun how I can do this? Please help me.

**Comment by meets2tarun** [comment]
From next time make a separate branch to work.
For reverting back the key, just edit the .travis.yml file to that of fossasia key in your forked repo master branch.

**Comment by meets2tarun** [comment]
@sandeepsajan0 Please squash your commits!

**Comment by xeon-zolt** [comment]
@sandeepsajan0 how removing lxqt power management  resolves the notifications issue. instead of that maybe adding the configuration so that it do not gives a notification about first time usage

**Comment by sandeepsajan0** [comment]
@xeon-zolt  both the methods are sufficient.
Because power daemon is responsible for starting up power-management(due to this notification occur on the desktop) every time during startup. 
So, after the turning off the power daemon, the issue is solved.

**Comment by xeon-zolt** [comment]
but you are removing it.

**Comment by sandeepsajan0** [comment]
yes, but As I think turning off the power daemon and removing the power-management both are doing same work here.

**Comment by xeon-zolt** [comment]
The issue is to disable the desktop notification not the power daemon and when I see the first notification it says configuration is missing so that can be solved in a better way by adding its configuration but still the other notifications are there to pollute the startup screen with notifications like lxqt panel notification.

**Comment by meets2tarun** [comment]
But we don't even need lxqt power management according to https://github.com/fossasia/labs.fossasia.org/issues/135

**Comment by tabesin** [comment]
This is a misunderstanding, Tarun. Mario meant the showing of confusing notifications at startup, i.e. fixing of the bug, not deactivation of the notifications demon and power management.

**Pull request closed without merging**
