### PR TITLE
added qq flags to apt

### LINKED ISSUE #429: quite flag for package manager to stop showing
add a -q flag to apt
build 1552 fossasia meilix travis ci

### PR DESCRIPTION
**Pull request by alok760**
### Short description
Fixes #429
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by xeon-zolt** [comment]
#LGTM

**Comment by tabesin** [comment]
For what reasons do you add -qq flags?

Have you checked if they make sense in the connection to the command you applied them to?

**Comment by xeon-zolt** [comment]
@tabesin i think its correct we don't require them to add too much to Travis logs

**Comment by pranav1698** [comment]
-q with apt will give less noisy and less verbose output,
With -qq will give the least possible verbose output

**Pull request merged**
