### PR TITLE
LXQt dekstop for meilix

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
#67 
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
lxqt
LXQt on meilix

**Comment by xeon-zolt** [comment]
by seeing the progress i think it is going to be a big pull request so to be sure it works good dont you think it should be broken into parts

**Comment by meets2tarun** [comment]
No, it's just a part only, meta packages rebuilding just made it look a bit big.

**Comment by xeon-zolt** [comment]
1361 files changed

**Comment by meets2tarun** [comment]
Reason we need to introduce initramfs-tools
https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1582270

**Comment by meets2tarun** [comment]
Link to the iso for testing: https://github.com/meets2tarun/meilix/releases/download/untagged-531274e1f804b4686c6a/meilix-zesty-20170717-i386.iso

**Comment by meets2tarun** [comment]
Big thanks to Mr. Yao Wei @medicalwei for the success of this PR.
Thanks to co-developer Mr. Harsh too @xeon-zolt 
Thanks to Mr. Mario @mariobehling too.

**Comment by meets2tarun** [comment]
For testing the iso from the FOSSASIA version of LXQt 
https://github.com/fossasia/meilix/releases/tag/untagged-d2c3d7386a7077f069cc

**Pull request merged**
