### PR TITLE
changed token

### PR DESCRIPTION
**Pull request by meets2tarun**
Changed the token to the earlier since its a the deployment failure.

### CODE REVIEW

**Comment by meets2tarun** [comment]
@Abhi2424shek It get passed for fossasia/meilix but again failed for meets2tarun/meilix (mine one).

**Comment by niccokunzmann** [comment]
A token can only be valid for one repository. Otherwise, people could for meilix and upload a hacked version to the official meilix github release.

**Comment by meets2tarun** [comment]
Then how can I able to deploy it successfully in my repository.

**Comment by niccokunzmann** [comment]
You can use your token in your repository. The meilix repository uses
its own. Then, you create the pull-request without the token.

Or, you can find a way to switch between several encrypted tokens of
whihc one works, e.g. by using environment variables.

**Comment by Abhi2424shek** [comment]
@meets2tarun as I have mentioned, please update the token for your repository and next time when you commit don't commit .travis.yml, simple. Also if you want we may go another way that is by putting the token in the dashboard.

**Comment by meets2tarun** [comment]
[#39](https://github.com/fossasia/meilix/issues/39)
@Abhi2424shek  Please close the issue.

**Comment by Abhi2424shek** [comment]
Thanks

**Pull request merged**
