### PR TITLE
Replaced gksu for nautilus-admin- (Solves- #352)

### LINKED ISSUE #352: gksu build dependency for systemlock debian package has been removed from ubuntu bionic 18.04
- Issue type: Bug report

### Short description

If you try to build the systemlock debian package, 
You will get this error: 
Unmet build dependencies: gksu

If you try to install gksu in  Ubuntu bionic 18.04 you will get this error:
Package gksu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'gksu' has no installation candidate

On searching this error on the internet, I found that: https://itsfoss.com/gksu-replacement-ubuntu/ 
It has been removed from the ubuntu

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 
 - Software source: 

### Steps to reproduce

1.  Try make the debian system package  
2.  You will get the unmet build dependencies error: gksu
3.  Installing gksu you will get no installation candidate error

### Expected behaviour

Build process should occur without any error

### PR DESCRIPTION
**Pull request by pranav1698**
### Short description
This replaces the dependency gksu with its alternative nautilus-admin
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #352

### CODE REVIEW

**Comment by pranav1698** [comment]
@tabesin With pcmanfm-qt we can use two methods as an alternative for gksu:
as given here: https://wiki.lxde.org/en/PCManFM#Run_as_root
Any alternative that you suggest?

**Comment by pranav1698** [comment]
OK @xeon-zolt @tabesin @meets2tarun what should be the next steps.

**Comment by tabesin** [comment]
Use lxqt-sudo instead of gksu

**Comment by pranav1698** [comment]
Okay making the changes

**Comment by pranav1698** [comment]
@tabesin please review now

**Comment by tabesin** [comment]
Have you tested it? 

Plus also under bionic?

**Comment by pranav1698** [comment]
I have done some research on this, pcmanfm-qt now uses lxqt-sudo by default for the root instead of gksu, lxqt-sudo works similar to gksu but I will still test it

**Comment by pranav1698** [comment]
@tabesin I tested it, lxqt-sudo must serve the purpose here

**Comment by tabesin** [comment]
With "test it" I meant just, does the functionality work out of the box and are packages in the repo available etc.

**Comment by pranav1698** [comment]
Yeah @tabesin it clears all the test that you have given, also it is a part of the repo

**Comment by pranav1698** [comment]
Okay let me open up a pr there for this issue

**Pull request closed without merging**
