### PR TITLE
Minimal Install of LXQt for the meilix ISO - (Solves- #468)

### LINKED ISSUE #468: Minimal Installation of lxqt in the Meilix
- Issue type: Feature request 

### Short description

In the current meilix build, we are installing the complete lxqt desktop with all the packages like audacious, sm-player, and other packages that is not required
I suggest a minimal installation with installation of the dependencies that are required for a minimal lxqt-desktop and the size of  the iso will also increase if the packages are installed in the meilix ISO using the generator.

### Usecase

Minimal installation of lxqt-desktop to decrease the size of ISO by default.

### PR DESCRIPTION
**Pull request by pranav1698**
### Short description
Minimal installation of lxqt for meilix ISO, this considerably decrease the size of the ISO without hampering the working of the ISO.
You can test the release here: https://github.com/pranav1698/meilix/releases/download/untagged-8565ebfb56a823bda4e9/meilix-xenial-20190416-amd64.iso  
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #468

### CODE REVIEW

**Comment by tabesin** [comment]
What are the precise effects of this change? What packages are not installed anymore?

**Comment by pranav1698** [comment]
In the present changes,
All the required dependencies will get installed like display manager, window manager, file manager (pcmanfm-qt) and panel. 
Some of the packages that are not installed,
Audio applications like: smplayer, audacious, mpv (not required as vlc has been provided)
Video applications like: smtube
Previously, we had two terminals qterminal and xterminal, but now only one terminal `xterminal` (xterminal remain the same)
Other functionalities remain the same 
Test release: https://github.com/pranav1698/meilix/releases/download/untagged-d69741408f122b37a611/meilix-xenial-20190418-amd64.iso

**Comment by tabesin** [comment]
What I asked for is a list that compares installed packages on the ISO with and without the patch, with the info which exact packages are not installed with the patch.

Please provide the list of packages that make the difference.

Hint:
run 
`sudo apt list --installed`
or 
`sudo dpkg -l`
on old and new iso and sent the output to the cloud. Then make a diff of both results.

Otherwise you could also experiment with the
` --dry-run`
parameter for apt-get install.

**Comment by tabesin** [comment]
The background of it is at follows: the optimal LXQT install may be something between the minimal and the extended install, that is without the superfluous packages as second terminals but yet there may be packages we want to have and install them individually. We need transparency not to miss out anything.

**Pull request merged**
