### PR TITLE
Installation of git, dropbox, vlc, chrome and oxygen icon

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
This PR will take care of installation of missing packages which are required and those packages are git, dropbox, vlc, chrome, and oxygen icon theme and gedit.
#67 
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by xeon-zolt** [comment]
#101 added oxygen icon theme to install to fix no icons in pcmanfm

**Comment by xeon-zolt** [comment]
@mariobehling I approved after checking the issue mentioned #67 and the changes which are installing the apps required in issue 67

**Comment by mariobehling** [comment]
@meets2tarun When do you update the PR so it follows best practices?

**Comment by meets2tarun** [comment]
@mariobehling I updated the commit message.
Testing iso link: https://github.com/meets2tarun/meilix/releases/tag/untagged-dda475ae220943e66e1e

**Comment by abishekvashok** [comment]
@meets2tarun nice job, the code looks good and it's working fine for now. But, please ensure you squash commits **not by web** but via the command line. It will make the PR look more professional as the online web editor does not indent commit messages properly.

**Pull request merged**
