### PR TITLE
[WIP] Adding a PPA

### PR DESCRIPTION
**Pull request by Abhi2424shek**
@mariobehling I have been working on adding a PPA with this PR.

But we cannot afford a git repository to be a PPA hosting the packages, hence we need a new domain or use an already present one for hosting the packages. After creating the domain and the code hosting server there, we will need to make the updates synced between this and that, we can achieve this easily with travis updating code on commits other than PRs. Now the problem is that we need a domain to host our packages which should not be managed by git or svn.

I would need your opinion on this will the community deliver it or shall I deliver for the community.

@mariobehling plese express your opinion and only after which will this Pr move on...

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
@mariobehling

**Comment by mariobehling** [comment]
@Abhi2424shek Thanks for your patience. It would be great, if you could set up a repo temporarily to get this working. Cheers.

**Comment by mariobehling** [comment]
@Abhi2424shek 

> But we cannot afford a git repository to be a PPA hosting the packages

Could you elaborate, what you mean by that? Why can't we use a GitHub repo?

**Comment by Abhi2424shek** [comment]
It's not supported to host your github repo as a PPA to supply the packages

**Comment by Abhi2424shek** [comment]
@mariobehling i would set it up for the organisation then so no worries! 👍

**Comment by mariobehling** [comment]
Ok, so I am merging this. Travis is not working yet, though.

**Comment by Abhi2424shek** [comment]
Travis has been fixed after this PR! Plus this PR was a work in progress sir. That's why i didn't 
 squash

Hah no probs then I will give another PR

**Comment by mariobehling** [comment]
Ok, thank you.

**Comment by Abhi2424shek** [comment]
@mariobehling please see slack for some more details...

**Pull request merged**
