### PR TITLE
modified plymouth theme files

### LINKED ISSUE #116: Debrand startup screen
- Issue type: Feature request 

### Short description

Technically Meilix is a Ubuntu derivate. When you boot up Meilix it says Ubuntu 17.04 in the load screen. You can disable that startup screen or debrand it or replace it by sth else as it confuses our users.

### Steps to reproduce

1. Generate ISO
2. Boot up Meilix 
3. Loading notice says Ubuntu 17.04

### Expected behaviour

A startup screen - if any - says meilix loading up or even "LinuxFriends Event Distribution"(or whatever the user wanted) loading but not Ubuntu 17.04

### Actual behaviour

You get informed that Ubuntu 17.04 is loading, together with the . . . . progress display.

### Hints

Look at Plymouth configuration and theming.

### PR DESCRIPTION
**Pull request by xeon-zolt**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message 
Fixes #116 

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by xeon-zolt** [comment]
I think we should remove the deb files of Plymouth and copy the files to chroot and apply them

**Comment by tabesin** [comment]
Better keep plymouth in a custom package to be debuild. So it is easier to remove it or replace it.

**Comment by tabesin** [comment]
Ah I see, I understand you have to debuild the meilix-artwork at build time to make the changes effective.

**Comment by xeon-zolt** [comment]
so i will add a modify the debuild script for that also

**Comment by tabesin** [comment]
Please note that currently login appears to be broken and that must relate to a recent commit. I am all in favour of a permissive approach towards breaking things and I don't like PR to hang and rott, it's just that we need to identify and fix the issue quickly. So please check if your changes broke it.

**Comment by xeon-zolt** [comment]
@tabesin nope they are not responsible for breaking login

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/pull/160
This is responsible.

**Pull request merged**
