### PR TITLE
Removed about lxqt from the the menu - (Solves -#121)

### LINKED ISSUE #121: Disable About LXQT label in menu
- Issue type: Feature request 

### Short description
Disable the display of the about-lxqt entry in the menu.
(on a user system this could be done via "menulibre"; then find out what it does)

fossasiatheme

### PR DESCRIPTION
**Pull request by pranav1698**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
The about lxqt section does not appear in the menu section now, 

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #121

Link for the release for testing :-  https://github.com/pranav1698/meilix/releases/tag/untagged-f865eb7afa7e020af162

### CODE REVIEW

**Comment by pranav1698** [comment]
The build because of the reason mentioned in the issue #346

**Comment by pranav1698** [comment]
Waiting for review @tabesin @meets2tarun

**Comment by tabesin** [comment]
Should consider cases where there are spaces..and pls sqsh

**Comment by pranav1698** [comment]
I think the spaces will not matter here as we are just adding a new line in the desktop using the $ address and the command will just add the same string that is written after the `a` character in the end of the file
I think spaces will not be a case here; it will be a case when we the substitution here we are just appending

**Comment by pranav1698** [comment]
I have squashed the commits.. @tabesin

**Pull request merged**
