### PR TITLE
Meilix booting into blank screen

### LINKED ISSUE #270: Meilix ISO boot into black screen
I tested the latest build of meilix and found that meilix boot into a black screen and where there nothing is visible.

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
Fixes #270 
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

I have returned to that commit which is working fine and then made the required changes above of that particular commit.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@meets2tarun There are merge conflicts. Can you resolve them?

**Comment by tabesin** [comment]
merge conflicts = api key

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/releases/tag/untagged-582f0863209939748aab
https://github.com/fossasia/meilix/releases/tag/untagged-bd1005bc8c0941c5aa1f

**Comment by niccokunzmann** [comment]
@meets2tarun Could you resolve the issue with the API key?
Maybe, in your own travis-ci.org repository configuration, you can override this without changing the .travis.yml file. I am curious if it works and guess people who fork it would like to know that, too.

**Comment by meets2tarun** [comment]
I don't think this will work

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix/issues/270#issuecomment-395822235

**Pull request closed without merging**
