### PR TITLE
Plymouth theming for meilix

### LINKED ISSUE #158: plymouth theming
plymouth-theme-ubuntu-text
plymouth-theme-ubuntu-logo

are the two theming packages in zesty. I suggest to download the source packages, hack them and generate a custom plymouth-theme-meilix-text and a plymouth-theme-meilix-logo deb package replacing the current artwork package.

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
Fixes #158 
Plymouth theming for the meilix desktop
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
Testing link to the changes:
https://github.com/meets2tarun/meilix/releases/tag/untagged-fae11eb6911d734e94d9

**Comment by tabesin** [comment]
No. this does not work. It is actually the same line as the one below with sudo, except that we changed the picked theme and added a ---verbose parameter to get more input.

Tarun: We need to regenerate the casper image. We create a new image but the casper image is the one used at boot time.

**Comment by meets2tarun** [comment]
NO, they are different, one for theme and the other for logo.
I tested it and you can also check through the link by running the ISO.

**Comment by tabesin** [comment]
I wrote this stuff.

**Comment by tabesin** [comment]
What we need is to put the kernel we regenerated into /casper
see 
https://help.ubuntu.com/community/LiveCDCustomization

**Comment by tabesin** [comment]
Or maybe that error message is the reason
https://ubuntuforums.org/showthread.php?t=2322684

**Comment by meets2tarun** [comment]
Desktop Recording of the ISO
https://drive.google.com/open?id=0BxePveCfPFgoYWVJZU4tWjFUQ0E

**Pull request merged**
