### PR TITLE
Updated artwork package version for the latest release - (Solves- #365)

### LINKED ISSUE #365: Updating the meilix build script for the debian package new release
- Issue type: Bug report 

### Short description

We have updated the version the artwork debian package to debian 1.0-2, 
Now we have to update the meilix build script to the artwork 1.0-2 

### Environment

 - Operating system: Ubuntu 18.04, travis
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3. 

### Expected behaviour

The build script should be updated for the artwork packages

### PR DESCRIPTION
**Pull request by pranav1698**
### Short description
This updates the artwork package version to the latest version in the build and chroot script, 
For setting the boot splash screen and the text screen
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

Fixes #365

### CODE REVIEW

**Comment by pranav1698** [comment]
@tabesin @meets2tarun @abishekvashok please review

**Comment by pranav1698** [comment]
@abishekvashok Please merge this also as it is causing failing of travis build

**Comment by pranav1698** [comment]
Yes @abishekvashok but for this pr, if you could merge so that the build does not fails

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
