### PR TITLE
Fix to not add changes made in the .travis.yml file

### LINKED ISSUE #148: Stop to commit Travis API key in the repository
- Issue type: Feature request 

### Short description

Every person has its own unique secure key included in the .travis.yml file and the idea is to not include the .travis.yml file is its been committed.

### PR DESCRIPTION
**Pull request by meets2tarun**
### Short description
I have:
- [x] There is a corresponding issue for this pull request.
- [x] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`
Fixes #148 
Every person has its own unique secure key included in the .travis.yml file and the idea is to not include the .travis.yml file is its been committed.
### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by tabesin** [comment]
Would break the build as travis pulls the files from the repo. You need to have this on your machine, not in the repo

**Comment by meets2tarun** [comment]
> Would break the build as travis pulls the files from the repo.

How, its not happening here and it's job is to ignore any commit made in that file.

**Comment by tabesin** [comment]
So what about checkouts?

**Comment by tabesin** [comment]
git upstream checkouts, like via travis

**Pull request closed without merging**
