### PR TITLE
adding SUSI Desktop app

### PR DESCRIPTION
**Pull request by xeon-zolt**
### Short description
I have:
- [ ] There is a corresponding issue for this pull request.
- [ ] Mentioned the Issue number in the pull request commit message `Fixes #<number> commit message`

- added the susi desktop electron app https://github.com/fossasia/susi_desktop 

### For the reviewers
I have:
- [ ] Reviewed this pull request by an authorized contributor.
- [ ] The reviewer is assigned to the pull request.

### CODE REVIEW

**Comment by meets2tarun** [comment]
@xeon-zolt Please check the request and make required changes.

**Comment by xeon-zolt** [comment]
@meets2tarun which request if your are talking about the coadcy the problrm is with the code of SUSI desktop app

**Comment by meets2tarun** [comment]
Let's go ahead, alright.
Paste the link so I can test them up.

**Comment by tabesin** [comment]
Let's test and fix the issues

**Pull request merged**
